---
- name: Get packages
  ansible.builtin.package_facts:
    manager: apt

- name: Install postgresql {{ postgresql_version }}
  when: ansible_facts.packages['postgresql-common'] is not defined
  notify:
    - restart postgresql
  block:
    - name: Update pkg cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Install gnupg
      ansible.builtin.apt:
        name:
          - gnupg2

    - name: Add repo key
      ansible.builtin.apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present

    - name: Cread source-file
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pgdg.list
        content: |
          deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main
        owner: root
        group: root
        mode: "0544"

    - name: Install postgresql server/client ver {{ postgresql_version }}
      ansible.builtin.apt:
        update_cache: true
        name:
          - postgresql-{{ postgresql_version }}
          - postgresql-client-{{ postgresql_version }}

- name: Change postgresql.conf 1/2
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    line: "listen_addresses = '*'"
    state: present
    insertbefore: '^port'
  notify:
    - restart postgresql

- name: Change postgresql.conf 2/2
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regex: '^(\s*ssl\s*=\s*on)\s*$'
    line: '#\1'
    backrefs: true
  notify:
    - restart postgresql

- name: Change pg_hba.conf 1/3
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regex: '^local *all *postgres *peer'
    state: absent
  notify:
    - restart postgresql

- name: Change pg_hba.conf 2/3
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^local *all *all *md5'
    line: "local   all             all                                     md5"
    insertbefore: '^local'
    firstmatch: true
  notify:
    - restart postgresql

- name: Change pg_hba.conf 2/3
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^host *all *all *{{ postgresql_subnet }} *md5'
    line: "host    all             all             {{ postgresql_subnet }}      md5"
    insertbefore: '^host'
    firstmatch: true
  notify:
    - restart postgresql
